Repository kuzzleio/sdk-c, pull requests merged in 2018-12, with the labels that each got.

#45 Add an enum for the state
  cgo/kuzzle/options.go
  include/internal/kuzzle_structs.h
Labels: changelog:new-features

#46 Fix struct destructors
  cgo/kuzzle/destructors.go
  cgo/kuzzle/go_to_c.go
  include/internal/kuzzle_structs.h
Labels: changelog:bug-fixes

#48 Keep enums without prefix in C++
  include/internal/kuzzle_structs.h
Labels: changelog:exclude
