Repository kuzzleio/sdk-c, pull requests merged in 2018-10, with the labels that each got.

#7 Add badge for build and link to S3 to README.md
  README.md
Labels: changelog:exclude

#9 Fix user rights
  cgo/kuzzle/destructors.go
  cgo/kuzzle/go_to_c.go
  include/kuzzlesdk.h
Labels: changelog:bug-fixes

#10 Fix Makefile for Android
  Makefile
  README.md
Labels: changelog:bug-fixes

#14 Kzl 624 push on s3 from dev
  .travis.yml
Labels: changelog:enhancements

#13 KZL-547 - update validateSpecification signature
  .travis.yml
  cgo/kuzzle/collection.go
Labels: changelog:enhancements

#19 Remove free
  cgo/kuzzle/go_to_c.go
Labels: changelog:bug-fixes

#22 Add default values for structs
  include/kuzzlesdk.h
Labels: changelog:enhancements
