Repository kuzzleio/sdk-c, pull requests merged in 2018-11, with the labels that each got.

#26 Use default value from Go for options and room_options
  cgo/kuzzle/options.go
  include/kuzzlesdk.h
Labels: changelog:enhancements

#27 Fix wrapping of options and room_options
  cgo/kuzzle/options.go
  include/kuzzlesdk.h
Labels: changelog:bug-fixes, do not merge

#28 Fix segfault
  cgo/kuzzle/options.go
Labels: changelog:bug-fixes

#32 Fix segfault bis
  cgo/kuzzle/options.go
Labels: changelog:bug-fixes

#30 [kzl-832] make document.count body argument optional
  cgo/kuzzle/document.go
Labels: do not merge

#29 Wrap the protocol
  README.md
  cgo/kuzzle/c_to_go.go
  cgo/kuzzle/kuzzle.go
  cgo/kuzzle/protocol.go
  cgo/kuzzle/query.go
  cgo/kuzzle/websocket.go
  include/kuzzlesdk.h
  include/protocol.h
Labels: changelog:breaking-changes

#34 fix errors dispatching
  cgo/kuzzle/protocol.go
Labels: changelog:bug-fixes

#36 Fix makefile dependencies
  .gitignore
  Makefile
Labels: changelog:bug-fixes, changelog:enhancements

#38 Implement realtime notification
  cgo/kuzzle/c_to_go.go
  cgo/kuzzle/protocol.go
  cgo/kuzzle/websocket.go
  include/protocol.h
Labels: changelog:new-features

#39 Rename and move headers
  Makefile
  cgo/kuzzle/auth.go
  cgo/kuzzle/c_to_go.go
  cgo/kuzzle/collection.go
  cgo/kuzzle/destructors.go
  cgo/kuzzle/document.go
  cgo/kuzzle/errors.go
  cgo/kuzzle/go_to_c.go
  cgo/kuzzle/index.go
  cgo/kuzzle/kuzzle.go
  cgo/kuzzle/memory_storage.go
  cgo/kuzzle/options.go
  cgo/kuzzle/protocol.go
  cgo/kuzzle/query.go
  cgo/kuzzle/realtime.go
  cgo/kuzzle/security.go
  cgo/kuzzle/server.go
  cgo/kuzzle/websocket.go
  include/internal/kuzzle_structs.h
  include/internal/protocol.h
  include/internal/sdk_wrappers_internal.h
Labels: changelog:enhancements, changelog:exclude

#41 Fix non-nil error value returned on success
  cgo/kuzzle/websocket.go
Labels: changelog:bug-fixes

#43 Fix multiple websockets and/or subscriptions conflicts
  cgo/kuzzle/kuzzle.go
  cgo/kuzzle/protocol.go
  cgo/kuzzle/websocket.go
Labels: changelog:bug-fixes
